import logging
from apscheduler.schedulers.background import BackgroundScheduler
from sqlmodel import Session, select
from database import engine
from models import MeetingSession, IntegrationSetting
from routers.sessions_upload import dispatch_emails, dispatch_platforms
import json
import asyncio
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

# Mock classes to simulate the expected Pydantic request models
class DispatchPlatformsRequest:
    pass

class DispatchEmailsRequest:
    pass

def check_and_dispatch_pending_sessions():
    """ Runs periodically to auto-dispatch sessions that exceeded their timeout. """
    with Session(engine) as session:
        # Check if auto-curation is enabled
        setting = session.exec(select(IntegrationSetting).where(IntegrationSetting.provider_name == "autoCuration")).first()
        if not setting:
            return
            
        try:
            config = json.loads(setting.config_json)
            is_enabled = config.get("isEnabled", False)
            timeout_hours = int(config.get("timeoutHours", 1))
            
            if not is_enabled:
                return
                
        except Exception as e:
            logger.error(f"Error parsing autoCuration settings: {e}")
            return

        pending_sessions = session.exec(select(MeetingSession).where(MeetingSession.status == "pending")).all()
        now = datetime.now() # Using local time since default_factory used datetime.now()
        
        for ms in pending_sessions:
            try:
                if not ms.created_at:
                    continue
                    
                try:
                    # In Python 3.11 fromisoformat handles almost all formats generated by .isoformat()
                    created_dt = datetime.fromisoformat(ms.created_at)
                except ValueError:
                    continue
                    
                # Calculate delta in hours
                if created_dt.tzinfo and now.tzinfo is None:
                    now = now.astimezone(created_dt.tzinfo)
                elif created_dt.tzinfo is None and now.tzinfo:
                    created_dt = created_dt.astimezone(now.tzinfo)
                    
                delta_hours = (now - created_dt).total_seconds() / 3600.0
                
                if delta_hours >= timeout_hours:
                    logger.info(f"Session {ms.id} exceeded auto-curation timeout ({delta_hours:.2f} >= {timeout_hours}). Auto-Dispatching...")
                    
                    # Both dispatch functions are async, we must run them in an event loop
                    # since APScheduler default workers are threaded, we create a new loop
                    loop = asyncio.new_event_loop()
                    asyncio.set_event_loop(loop)
                    
                    try:
                        loop.run_until_complete(dispatch_platforms(ms.id, DispatchPlatformsRequest(), session))
                    except Exception as e:
                        logger.error(f"Auto-dispatch platforms error for session {ms.id}: {e}")
                        
                    try:
                        loop.run_until_complete(dispatch_emails(ms.id, DispatchEmailsRequest(), session))
                    except Exception as e:
                        logger.error(f"Auto-dispatch emails error for session {ms.id}: {e}")
                    
                    loop.close()
                    
                    # Mark as processed so it doesn't get grabbed again
                    ms.status = "processed"
                    session.add(ms)
                    session.commit()
            except Exception as e:
                logger.error(f"Error evaluating session {ms.id} for auto-curation: {e}")


scheduler = BackgroundScheduler()
# Runs every 5 minutes
scheduler.add_job(check_and_dispatch_pending_sessions, 'interval', minutes=5)

def start_cron():
    scheduler.start()
    logger.info("Background Cron Scheduler started")

def stop_cron():
    scheduler.shutdown()
    logger.info("Background Cron Scheduler stopped")
